/*
 * This source file was generated by the Gradle 'init' task
 */
package learn.sparkJava;

import org.junit.jupiter.api.Test;

class SparkAppTest {
    @Test void appHasAGreeting() {
        SparkApp classUnderTest = new SparkApp();
    }
}
